ecommerce/config/routes.rb
Rails.application.routes.draw do

  resources :hotels do
    resources :items
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "hotels#index"
end

ecommerce/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ecommerce/app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :items
end

ecommerce/app/models/item.rb
class Item < ApplicationRecord
  belongs_to :hotel, dependent: :destroy
end

ecommerce/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ecommerce/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :description)
    end
end

ecommerce/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_hotel
  p  before_action :set_item, only: %i[ show edit update destroy ]
  # GET /items or /items.json
  def index
    @items = @hotel.items
    # render plain: @items.each { |x| x }
  end

  # GET /items/1 or /items/1.json
  def show
    @items = @hotel.items
  end

  # GET /items/new
  def new
    @message = @hotel.items.build
  end

  # GET /items/1/edit
  def edit
    @items = @hotel.items
  end

  # POST /items or /items.json
  def create
    # @item = Item.new(item_params)
    @item = @hotel.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to hotel_items_url(@hotel, @item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to hotel_items_url(@hotel, @item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to hotel_items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_hotel
    @hotel = Hotel.find(params[:hotel_id])
  end
    def set_item
      @hotel = Hotel.find(params[:hotel_id])
      @items = @hotel.items.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description)
    end
end

ecommerce/app/helpers/application_helper.rb
module ApplicationHelper
end

ecommerce/app/helpers/hotels_helper.rb
module HotelsHelper
end

ecommerce/app/helpers/items_helper.rb
module ItemsHelper
end

ecommerce/app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |form| %>
  <% if hotel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ecommerce/app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
  <p>
    <strong>Name:</strong>
    <%= hotel.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= hotel.description %>
  </p>

</div>

ecommerce/app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Show this hotel", @hotel %> |
  <%= link_to "Back to hotels", hotels_path %>
</div>

ecommerce/app/views/hotels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hotels</h1>

<div id="hotels">
  <% @hotels.each do |hotel| %>
    <%= render hotel %>
    <p>
      <%= link_to "Show this hotel", hotel %>
    </p>
  <% end %>
</div>

<%= link_to "New hotel", new_hotel_path %>

ecommerce/app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Back to hotels", hotels_path %>
</div>

ecommerce/app/views/hotels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hotel %>

<div>
  <%= link_to "Edit this hotel", edit_hotel_path(@hotel) %> |
  <%= link_to "Back to hotels", hotels_path %>
  <%= link_to "Click Here for Menu", hotel_items_path(@hotel) %>
  <%= button_to "Destroy this hotel", @hotel, method: :delete %>
</div>

ecommerce/app/views/items/_form.html.erb
<%= form_with(model: [@hotel, item]) do |form| %>
  <% if @items.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :hotel_id, style: "display: block" %>
    <%= form.text_field :hotel_id %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ecommerce/app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= item.description %>
  </p>
</div>

ecommerce/app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<!--<div>-->
<!--  <%#= link_to "Show this item", @item %> |-->
  <%#= link_to "Back to items", hotel_items_path %>
<!--</div>-->

<div>
  <%= link_to "Show this item",[@hotel, @item] %>
  <%= link_to "Back to items", [@hotel, :items] %>
</div>

ecommerce/app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%#= link_to "Show this item", 'items/item', item: @items.find(1) %>
      <%#= link_to "Show this item", hotel_items_path(@hotel , :items) %>
      <%= link_to "Show this item", [@hotel, item] %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_hotel_item_path %>

ecommerce/app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", hotel_items_path(@hotel) %>
</div>

ecommerce/app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @items %>

<div>
  <%= link_to "Edit this item", edit_hotel_item_path([@hotel,@items]) %> |
  <%#= link_to "Back to items", hotel_items_path %>
  <%= link_to "Back to items", [@hotel, :items] %>

  <%#= button_to "Destroy this item", @item, method: :delete %>
  <%#= button_to "Destroy this item", hotel_item_path(@hotel,@items), method: :delete %>
  <%= button_to "Destroy this item", [@hotel, @item], method: :delete %>
</div>

ecommerce/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoREcommerceApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>